version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=docker_dz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis

  api:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build: .
    depends_on:
      - db
      - redis
    command: celery -A config worker -l INFO

  celery_beat:
    build: .
    depends_on:
      - db
      - redis
      - celery_worker
    command: sh -c "sleep 30 && celery -A config beat -l info --loglevel=info"

volumes:
  db:
