# Generated by Django 4.2.3 on 2023-08-14 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course', verbose_name='Превью (картинка)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('amount', models.FloatField(verbose_name='Цена')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson', verbose_name='Превью (картинка)')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата платежа')),
                ('paid', models.FloatField(verbose_name='Cумма оплаты')),
                ('paid_method', models.CharField(choices=[('Сashless', 'Безналичный расчет'), ('Cash', 'Наличными')], default='Сashless', max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(default='requires_payment_method', max_length=20, verbose_name='Статус')),
                ('intent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежного намерения')),
                ('method_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID метода оплаты')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_training.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
