# Generated by Django 4.2.3 on 2023-07-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сourse',
            new_name='Course',
        ),
    ]
