# Generated by Django 4.2.3 on 2023-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.FloatField(default=50000, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Ожидает оплаты'), ('Success', 'Оплачено'), ('Canceled', 'Отмена оплаты')], default='Waiting', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_method',
            field=models.CharField(choices=[('Сashless', 'Безналичный расчет'), ('Cash', 'Наличными')], default='Сashless', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
