# Generated by Django 4.2.3 on 2023-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0007_payment_intent_id_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID метода оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='intent_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежного намерения'),
        ),
    ]
