# Generated by Django 4.2.3 on 2023-07-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0008_payment_method_id_alter_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего обновления'),
        ),
    ]
